# Generated by Django 5.0.6 on 2024-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kindof', models.FloatField(default=0.0)),
                ('descrip', models.CharField(max_length=50)),
            ],
        ),
    ]
