# Generated by Django 5.0.6 on 2024-07-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/150', max_length=2000),
        ),
    ]
