# Generated by Django 5.0.6 on 2024-07-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='post',
            name='director',
        ),
        migrations.RemoveField(
            model_name='post',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
    ]
