# Generated by Django 5.0.6 on 2024-07-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_ideastar'),
        ('tools', '0002_alter_tool_kindof_alter_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.tool'),
        ),
    ]
